name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: macos-latest
        strategy:
            matrix:
                target: [aarch64-apple-darwin, x86_64-apple-darwin]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}

            - name: Build
              run: cargo build --target ${{ matrix.target }} --release

            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  name: mac-soft-rs_${{ github.ref_name }}_${{ matrix.target }}
                  files: target/${{ matrix.target }}/release/mac-soft-rs
