name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: macos-latest
        strategy:
            matrix:
                target: [aarch64-apple-darwin, x86_64-apple-darwin]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}

            - name: Build
              run: cargo build --target ${{ matrix.target }} --release

              run: mv target/aarch64-apple-darwin/release/mac-soft-rs target/aarch64-apple-darwin/release/mac-soft-rs-arm64

            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  name: ${{ github.ref_name }}
                  files: |
                      target/x86_64-apple-darwin/release/mac-soft-rs
                      target/aarch64-apple-darwin/release/mac-soft-rs-arm64
